"""Minimal text renderer for a subset of Microsoft's DEQ (.deq) device DSL.

This module renders plain strings for ``CODE``/``GADGET``/``COMPOSE`` blocks.
It is intentionally dependency-free (no import of the ``deq`` package) so
``lightstim``'s export path works whether or not ``deq`` happens to be
installed. ``lightstim.deq.validate`` separately uses the real ``deq``
package, when available, to parse this text back and run its own spec
validators against it.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Mapping, Sequence

GENERATED_HEADER = "# Generated by lightstim.deq; do not edit by hand."


@dataclass(frozen=True)
class PauliProduct:
    """A same- or mixed-basis Pauli product, e.g. ``Z0*Z1*Z3*Z4``."""

    terms: tuple[tuple[str, int], ...]

    @classmethod
    def from_dict(cls, pauli: Mapping[int, str]) -> "PauliProduct":
        return cls(tuple(sorted(((p, q) for q, p in pauli.items()), key=lambda t: t[1])))

    def __str__(self) -> str:
        return "*".join(f"{pauli}{qubit}" for pauli, qubit in self.terms)


@dataclass(frozen=True)
class Instruction:
    """A single physical instruction, e.g. ``CX 1 9 10 2`` or bare ``TICK``."""

    name: str
    targets: tuple[int, ...] = ()

    def render(self) -> str:
        if not self.targets:
            return self.name
        return f"{self.name} " + " ".join(str(t) for t in self.targets)


def repeat(count: int, inner_lines: Sequence[str]) -> list[str]:
    """Render a structural ``REPEAT count { ... }`` block as a list of lines.

    ``inner_lines`` are gadget-application lines (e.g. ``"SyndromeExtraction 0"``),
    not raw instructions — DEQ's REPEAT calls a named gadget by index rather
    than duplicating an inlined instruction body.
    """
    lines = [f"REPEAT {count} {{"]
    lines.extend(f"    {line}" for line in inner_lines)
    lines.append("}")
    return lines


@dataclass
class CodeBlock:
    name: str
    n: int
    k: int
    d: int | None
    logical_x: PauliProduct
    logical_z: PauliProduct
    stabilizers: list[PauliProduct]

    def render(self) -> str:
        params = f"[[{self.n},{self.k},{self.d}]]" if self.d is not None else f"[[{self.n},{self.k}]]"
        stabilizers = " ".join(str(s) for s in self.stabilizers)
        return (
            f"CODE {self.name} {params} {{\n"
            f"    LOGICAL {self.logical_x} {self.logical_z}\n"
            f"    STABILIZER {stabilizers}\n"
            f"}}"
        )


@dataclass
class GadgetBlock:
    name: str
    lines: list[str] = field(default_factory=list)

    def render(self) -> str:
        body = "\n".join(f"    {line}" for line in self.lines)
        return f"GADGET {self.name} {{\n{body}\n}}"


@dataclass
class ComposeBlock:
    name: str
    lines: list[str] = field(default_factory=list)

    def render(self) -> str:
        body = "\n".join(f"    {line}" for line in self.lines)
        return f"COMPOSE {self.name} {{\n{body}\n}}"


@dataclass
class ProgramBlock:
    """A ``PROGRAM Name { ... }`` definition — the transpilable, runnable entry
    point ``python -m deq transpile --program Name`` compiles, as opposed to a
    ``COMPOSE`` block (a reusable library building block, not itself runnable).
    """

    name: str
    lines: list[str] = field(default_factory=list)

    def render(self) -> str:
        body = "\n".join(f"    {line}" for line in self.lines)
        return f"PROGRAM {self.name} {{\n{body}\n}}"


def document(*blocks: CodeBlock | GadgetBlock | ComposeBlock | ProgramBlock) -> str:
    """Join top-level blocks with a provenance header and blank-line separators."""
    parts = [GENERATED_HEADER] + [block.render() for block in blocks]
    return "\n\n".join(parts) + "\n"
