import numpy as np
from typing import Tuple, List

# Linear Algebra Utils

def row_echelon(mat, reduced=False):
    r"""Converts a binary matrix to (reduced) row echelon form via Gaussian Elimination, 
    also works for rank-deficient matrix. Unlike the make_systematic method,
    no column swaps will be performed.

    Input 
    ----------
    mat : ndarry
        A binary matrix in numpy.ndarray format.
    reduced: bool
        Defaults to False. If true, the reduced row echelon form is returned. 
    
    Output
    -------
    row_ech_form: ndarray
        The row echelon form of input matrix.
    rank: int
        The rank of the matrix.
    transform: ndarray
        The transformation matrix such that (transform_matrix@matrix)=row_ech_form
    pivot_cols: list
        List of the indices of pivot num_cols found during Gaussian elimination
    """

    m, n = np.shape(mat)
    # Don't do "m<=n" check, allow over-complete matrices
    mat = np.copy(mat)
    # Convert to bool for faster arithmetics
    mat = mat.astype(bool)
    transform = np.identity(m).astype(bool)
    pivot_row = 0
    pivot_cols = []

    # Allow all-zero column. Row operations won't induce all-zero columns, if they are not present originally.
    # The make_systematic method will swap all-zero columns with later non-all-zero columns.
    # Iterate over cols, for each col find a pivot (if it exists)
    for col in range(n):
        # Select the pivot - if not in this row, swap rows to bring a 1 to this row, if possible
        if not mat[pivot_row, col]:
            # Find a row with a 1 in this column
            swap_row_index = pivot_row + np.argmax(mat[pivot_row:m, col])
            # If an appropriate row is found, swap it with the pivot. Otherwise, all zeroes - will loop to next col
            if mat[swap_row_index, col]:
                # Swap rows
                mat[[swap_row_index, pivot_row]] = mat[[pivot_row, swap_row_index]]
                # Transformation matrix update to reflect this row swap
                transform[[swap_row_index, pivot_row]] = transform[[pivot_row, swap_row_index]]

        if mat[pivot_row, col]: # will evaluate to True if this column is not all-zero
            if not reduced: # clean entries below the pivot 
                elimination_range = [k for k in range(pivot_row + 1, m)]
            else:           # clean entries above and below the pivot
                elimination_range = [k for k in range(m) if k != pivot_row]
            for idx_r in elimination_range:
                if mat[idx_r, col]:    
                    mat[idx_r] ^= mat[pivot_row]
                    transform[idx_r] ^= transform[pivot_row]
            pivot_row += 1
            pivot_cols.append(col)

        if pivot_row >= m: # no more rows to search
            break

    rank = pivot_row
    row_ech_form = mat.astype(int)

    return [row_ech_form, rank, transform.astype(int), pivot_cols]


def create_lambda_matrix(n: int) -> np.ndarray:
    """
    Creates the standard symplectic form Lambda for Interleaved format.
    Lambda = Block Diag([0 1; 1 0], ...)
    
    Args:
        n: Number of qubits.
    
    Returns:
        (2n, 2n) numpy array (uint8). Lambda = [0 I_n; I_n 0]
    """
    # Simply create it every time. Fast enough for construction phase.
    L = np.zeros((2*n, 2*n), dtype=np.uint8)
    idx = np.arange(n)
    L[idx, n+idx] = 1
    L[n+idx, idx] = 1

    return L

def check_commutativity(mat_a: np.ndarray, mat_b: np.ndarray) -> np.ndarray:
    """
    Vectorized check of commutation between two sets of Pauli strings.
    Commutation(P, Q) = P @ Lambda @ Q.T (mod 2)
    
    Args:
        mat_a: (N_a, 2*num_qubits) matrix.
        mat_b: (N_b, 2*num_qubits) matrix.
        
    Returns:
        (N_a, N_b) binary matrix. [i, j] = 1 if mat_a[i] anti-commutes with mat_b[j].
    """
    # Sanity checks
    
    if mat_a.shape[1] != mat_b.shape[1]:
        raise ValueError(f"Matrices must have the same number of columns. "
                        f"mat_a has {mat_a.shape[1]} columns, mat_b has {mat_b.shape[1]} columns")
    
    if mat_a.shape[1] % 2 != 0:
        raise ValueError(f"Number of columns must be even (2*num_qubits). Got {mat_a.shape[1]} columns")
        
    n = mat_a.shape[1] // 2
    L = create_lambda_matrix(n)
    
    # A @ L @ B.T
    return (mat_a @ L @ mat_b.T) % 2

def solve_linear_decomposition(basis: np.ndarray, targets: np.ndarray) -> Tuple[np.ndarray, np.ndarray, List[int]]:
    """
    Solves for x in: x @ basis = targets (over GF(2)).
    
    Args:
        basis: (M, 2N) matrix.
        targets: (K, 2N) matrix.
        
    Returns:
        coeffs: (K, M) matrix. Coefficients relative to the ORIGINAL basis.
                Only valid/meaningful if is_dependent[k] is True.
        is_dependent: (K,) boolean. True if target[k] is strictly generated by basis.
        new_basis_indices: List[int]. Indices of 'targets' (0 to K-1) that represent 
                           NEW linear independent dimensions (Logical Basis).
                           These are the 'pivots' found in the target section.
    """
    if basis.shape[0] == 0:
        # If basis is empty, we just RREF targets to find self-dependencies
        system = targets.T
        n_basis = 0
    else:
        system = np.hstack([basis.T, targets.T])
        n_basis = basis.shape[0]

    n_targets = targets.shape[0]
    
    # Run RREF
    rref, rank, transform, pivot_cols = row_echelon(system, reduced=True)
    
    coeffs = np.zeros((n_targets, n_basis), dtype=np.uint8)
    is_dependent = np.ones(n_targets, dtype=bool)
    new_basis_indices = []
    
    # Map RREF rows to Basis Indices
    row_to_basis_map = {}
    
    for r, p_col in enumerate(pivot_cols):
        if p_col < n_basis:
            row_to_basis_map[r] = p_col
        else:
            # This pivot belongs to a Target!
            target_idx = p_col - n_basis
            new_basis_indices.append(target_idx)
            # A pivot is by definition independent of previous columns
            is_dependent[target_idx] = False

    # Extract Coefficients for DEPENDENT Rows
    for k in range(n_targets):
        # If this target is a New Basis Pivot, we already marked it independent.
        # In this case, leave its coeffs as 0 relative to old basis.
        if not is_dependent[k]:
            continue
            
        col_idx = n_basis + k
        target_col_vec = rref[:, col_idx]
        nonzero_rows = np.where(target_col_vec)[0]
        
        for r in nonzero_rows:
            if r in row_to_basis_map:
                basis_idx = row_to_basis_map[r]
                coeffs[k, basis_idx] = 1
            else:
                # This row depends on both Old Basis and Previous Targets.
                # We mark it as independent and set its coeffs to 0.
                # Note: We didn't give the coeffs under the extended basis (Old Basis + pivot Targets)
                is_dependent[k] = False
                coeffs[k, :] = 0 
                break
                
    return coeffs, is_dependent, new_basis_indices