"""
Table 2 Verification: Correctness validation with open-source references.

Covers both sections of Table 2:

  Part 1 — Rotated Surface Code (vs Stim built-in generator)
    d = 3, 5, 7  |  Z-memory, circuit-level noise, rounds = d
    Checks: detector count match + LER ratio (AutoDEM / Stim)
    LER ratios: loaded from precompute/hq_verification.json
                (pre-measured: 1e9 shots at p=1e-3; too slow to re-run inline)

  Part 2 — BB Code Memory (vs published reference, gongaa / IBM [10,36])
    [[72,12,6]]   rounds=6   |  [[144,12,12]]  rounds=12
    Checks: our detector count vs published reference count
    Ref counts use Z-only convention: n_Z_stab × rounds (gongaa formula)
    LightStim generates both X- and Z-type detectors → our count is higher

Output: precompute/table2.json  (one entry per row in Table 2)

Usage:
    venv/bin/python paper_artifact/table/table2_verification.py
"""
import sys, json
sys.path.insert(0, '/home/xiang/workspace/LightStim')

import stim
from pathlib import Path

from lightstim.qec_code.surface_code.rotated.code_patch import RotatedSurfaceCode
from lightstim.qec_code.surface_code.rotated.SE_block import (
    RotatedSurfaceCodeExtractionBlock as RotatedSEBlock,
)
from lightstim.qec_code.BB_code.code_patch import BBCode
from lightstim.qec_code.BB_code.SE_block import BBCodeExtractionBlock
from lightstim.ir.qec_system import QECSystem
from lightstim.protocols.memory import MemoryExperiment
from lightstim.noise.config import NoiseConfig

# ── Paths ─────────────────────────────────────────────────────────────────────
REPO = Path('/home/xiang/workspace/LightStim')
PRECOMPUTE = REPO / 'paper_artifact' / 'table' / 'precompute'
PRECOMPUTE.mkdir(parents=True, exist_ok=True)

_NC = NoiseConfig(p_1q=0, p_2q=0, p_meas=0, p_reset=0)

# ── Load pre-measured LER ratios (Rotated SC) ─────────────────────────────────
# Generated by archive/tests_dev/verify_hq.py at p=1e-3 (circuit-level).
# Shot counts: 1e9 for d=3,5 and 1e8 for d=7. ~12h total.
# Raw log: paper_artifact/table/results/hq_verify_log.txt
_hq_path = PRECOMPUTE / 'hq_verification.json'
if _hq_path.exists():
    _hq_data = {r['d']: r for r in json.load(open(_hq_path))}
else:
    _hq_data = {}
    print("WARNING: precompute/hq_verification.json not found — LER ratios will be missing.")
    print("         Run archive/tests_dev/verify_hq.py to generate it (~12h).")

# ── Published reference counts (BB codes, gongaa/IBM convention) ───────────────
# Ref uses Z-only detectors: n_Z_stab × rounds.
# LightStim counts both X- and Z-type detectors → 'Ours' is larger.
BB_REF = {
    '72,12,6':   432,   # n_Z=72,  rounds=6:  72×6=432
    '144,12,12': 1728,  # n_Z=144, rounds=12: 144×12=1728
}

results = {}

# =============================================================================
# Part 1: Rotated Surface Code vs Stim built-in
# =============================================================================
print("\n=== Part 1: Rotated SC vs Stim (detector count + LER ratio) ===")
print(f"{'d':>3}  {'Stim det':>9}  {'Ours det':>9}  {'Match':>6}  {'LER ratio':>10}")
print("-" * 46)

for d in [3, 5, 7]:
    # Stim reference circuit (circuit-level noise at p=1e-3 for DEM comparison)
    stim_circ = stim.Circuit.generated(
        'surface_code:rotated_memory_z',
        rounds=d, distance=d,
        after_clifford_depolarization=1e-3,
        before_round_data_depolarization=1e-3,
        before_measure_flip_probability=1e-3,
        after_reset_flip_probability=1e-3,
    )
    stim_det = stim_circ.num_detectors

    # LightStim circuit (noiseless — detector count is noise-independent)
    patch = RotatedSurfaceCode(distance=d)
    system = QECSystem()
    system.add_patch(patch)
    our_circ = MemoryExperiment(
        system, RotatedSEBlock, rounds=d,
        noise_params=_NC, noise_model='circuit_level', basis='Z',
    ).build()
    our_det = our_circ.num_detectors

    det_match = stim_det == our_det
    hq = _hq_data.get(d, {})
    ratio = hq.get('ratio')
    ratio_str = f"{ratio:.4f}×" if ratio else "—  (run verify_hq.py)"

    print(f"  d={d}  {stim_det:>9}  {our_det:>9}  {'✓' if det_match else '✗':>6}  {ratio_str:>14}")

    results[f'rotated_sc_d{d}'] = {
        'protocol': 'Rotated SC',
        'instance': f'd={d}',
        'stim_det': stim_det,
        'our_det': our_det,
        'det_match': det_match,
        'ler_ratio': ratio,
        'stim_ler': hq.get('stim_ler'),
        'our_ler': hq.get('autodem_ler'),
        'shots': hq.get('shots'),
        'p': hq.get('p', 1e-3),
    }

# =============================================================================
# Part 2: BB Code Memory vs published reference
# =============================================================================
print("\n=== Part 2: BB Code Memory vs published ref (detector count) ===")
print(f"{'Code':<16}  {'r':>3}  {'Ref det':>8}  {'Ours det':>9}  {'Excess':>8}  {'Note'}")
print("-" * 70)

_BB_A = [[3, 0], [0, 1], [0, 2]]
_BB_B = [[0, 3], [1, 0], [2, 0]]

BB_CONFIGS = [
    ('72,12,6',   dict(l=6,  m=6, A=_BB_A, B=_BB_B), 6),
    ('144,12,12', dict(l=12, m=6, A=_BB_A, B=_BB_B), 12),
]

for code_label, bb_params, rounds in BB_CONFIGS:
    patch = BBCode(**bb_params)
    system = QECSystem()
    system.add_patch(patch)
    circ = MemoryExperiment(
        system, BBCodeExtractionBlock, rounds=rounds,
        noise_params=_NC, noise_model='circuit_level', basis='Z',
    ).build()
    our_det = circ.num_detectors
    ref_det = BB_REF[code_label]
    excess = our_det - ref_det
    n_x_stab = len(patch.syndrome_indices_x)
    n_z_stab = len(patch.syndrome_indices_z)

    note = f"+{excess} X-type dets (LightStim adds X-stab detectors; gongaa counts Z only)"
    print(f"  [[{code_label}]]  r={rounds}  {ref_det:>8}  {our_det:>9}  +{excess:>6}  {note}")

    results[f'bb_{code_label}_r{rounds}'] = {
        'protocol': 'BB Memory',
        'instance': f'[[{code_label}]]',
        'rounds': rounds,
        'ref_det': ref_det,
        'our_det': our_det,
        'excess': excess,
        'n_x_stab': n_x_stab,
        'n_z_stab': n_z_stab,
        'ref_convention': 'Z-only: n_Z_stab × rounds (gongaa/IBM)',
    }

# =============================================================================
# Save and summary
# =============================================================================
out_path = PRECOMPUTE / 'table2.json'
with open(out_path, 'w') as f:
    json.dump(results, f, indent=2)

print(f"\nSaved to {out_path}")
print("\n" + "=" * 70)
print("TABLE 2 SUMMARY")
print("=" * 70)
print(f"{'Protocol':<20} {'Instance':<16} {'Det Ref':>8} {'Det Ours':>9} {'LER ratio':>10}")
print("-" * 70)
for k, v in results.items():
    det_ref = v.get('stim_det') or v.get('ref_det', '—')
    det_our = v.get('our_det', '—')
    ratio = v.get('ler_ratio')
    ratio_str = f"{ratio:.3f}×" if ratio else "—"
    print(f"  {v['protocol']:<18} {v['instance']:<16} {det_ref:>8} {det_our:>9} {ratio_str:>10}")
print("=" * 70)
print("\nNotes:")
print("  Rotated SC LER ratios from precompute/hq_verification.json")
print("  (1e9 shots d=3,5; 1e8 shots d=7; p=1e-3; circuit-level noise)")
print("  BB excess detectors = X-type stabilizer measurements (LightStim)")
print("  vs Z-only convention used by gongaa/IBM reference [10,36]")
